server:
  port: 20001
# 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always
#  servlet:
#    context-path: /coupon-template

spring:
  application:
    name: coupon-customer-serv
  datasource:
    # mysql数据源
    username: root
#    password:
    url: jdbc:mysql://127.0.0.1:3306/geekbang_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: GeekbangCouponHikari
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    # password:
#    # 连接超时时间
#    timeout: 10000

logging:
  level:
    com.broadview.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

